/* eslint-disable no-unused-vars */
export enum LOCAL_STORAGE_KEYS {
  TOKEN = 'TOKEN_USER',
  REFRESH_TOKEN = 'REFRESH_TOKEN_USER',
  IP_ADDRESS = 'IP_ADDRESS',
  DEVICE_NAME = 'DEVICE_NAME',
  LANGUAGE = 'LANGUAGE',
}
